server:
  port: 11000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.106:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # nacos server
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  # nacos注册中心需要每个服务都有对应应用的名字
  application:
    name: gulimall-ware
  # 返回json修改时间戳
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # 配置rabbitmq
  rabbitmq:
    host: 192.168.31.106
    port: 5672
    virtual-host: /
    ## 开启手动ack
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  ## *表示不只是扫描类路径，连依赖路径下的xml文件都一起扫描
  mapper-locations: classpath*:/mapper/**/*.xml
  ## 主键自增
  global-config:
    db-config:
      id-type: auto

# 打印日志，调整日志等级--SpringCloud提供的日志配置
logging:
  level:
    com.atguigu: debug